name: docker publish with tag manually

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag of the new docker image.'     
        required: true
        default: latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: 3arthqu4ke/headlessmc:${{ github.event.inputs.tag }}
          
